# Generated by Django 4.1.6 on 2023-02-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=30)),
                ('mclr', models.CharField(max_length=20)),
                ('mfeatures', models.CharField(max_length=40)),
                ('ram', models.CharField(max_length=20)),
                ('rom', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
